// This file is automatically generated from your CSS. Any edits will be overwritten.
export const menuToggle: string;
export const smallScreen: string;
export const largeScreen: string;
export const menu: string;
