// This file is automatically generated from your CSS. Any edits will be overwritten.
export const smallScreen: string;
export const largeScreen: string;
export const header: string;
export const active: string;
