// This file is automatically generated from your CSS. Any edits will be overwritten.
export const recommendation: string;
export const feedback: string;
export const accept: string;
export const reject: string;
