// This file is automatically generated from your CSS. Any edits will be overwritten.
export const instructions: string;
export const onscreen: string;
export const chefSprite: string;
export const talking: string;
export const talk: string;
export const chefBox: string;
export const offscreen: string;
export const speechBubble: string;
export const content: string;
