// This file is automatically generated from your CSS. Any edits will be overwritten.
export const onscreen: string;
export const transitioning: string;
export const caption: string;
export const speechBubble: string;
export const chefSprite: string;
export const talking: string;
export const talk: string;
export const exiting: string;
export const exit: string;
export const entering: string;
export const enter: string;
export const chefBox: string;
export const instructions: string;
