// This file is automatically generated from your CSS. Any edits will be overwritten.
export const procurement: string;
export const methods: string;
export const cook: string;
export const deliver: string;
